from setuptools import setup

setup(
    name="newk",
    version="1.0.0",
    author="srcsdk",
    author_email="srcsdk@users.noreply.github.com",
    description="feed aggregator and news reader",
    url="https://github.com/srcsdk/newk",
    py_modules=[
        "alerts",
        "api_feeds",
        "arxiv",
        "bookmarks",
        "dedup",
        "export",
        "finance",
        "gui_app",
        "health",
        "preferences",
        "preview",
        "quality",
        "reading",
        "rss_parser",
        "scheduler",
        "scrape",
        "stats",
        "summarize",
        "tags",
        "validate",
    ],
    python_requires=">=3.8",
    install_requires=[
        "feedparser",
        "requests",
        "beautifulsoup4",
        "lxml",
    ],
    entry_points={
        "console_scripts": [
            "newk=rss_parser:main",
            "newk-scrape=scrape:main",
            "newk-feeds=api_feeds:main",
        ],
    },
)
